---
- name: vape pen set
  title: Cannabis Oil Vaporization Set
  description:
    - Designed for on-the-go enjoyment, this premium vape set includes our Single Origin cannabis oil. Use throughout the day to incite creativity, calm the mind or deepen relaxation levels. 
    - Save yourself time and effort, this one cartridge can be used for endless occasions. The perfect dose of goodness anytime you need it — sunup to sundown. 
    - Includes battery, 500mg cartridge and charger.  Solvent Free. Product tested and held  to the highest standards for purity and consistent THC potency.
    - '<i>Experience: A clear-headed, focused high perfect for daytime and nighttime use.</i>'
  thumb: pen_set_thumb.jpg
  image: pen_set.jpg
  detail:

    - left: THC
      right: '>85%'

    - left: STRAIN
      right: Hybrid

    - left: PRODUCT ORIGIN
      right: Humboldt County, CA

- name: rise
  title: Solvent-Free Single Origin Cartridge Refill
  description: 
    - 'Mornings just got brighter. Our Rise, all-natural, single origin oil cartridges are available in 4 different terpene enriched flavors: Dank Berry, Enlighten”mint”, TropiCali and Natural.'
    - '<i>Select a tone to enhance your day:</i>'
  thumb: rise_thumb.jpg
  image: rise.jpg
  flavors:
    - name: Dank Berry
      desc: 
        - Imagine waking up feeling completely refreshed and ready to conquer the day.
        - 'Feel: Creative, alert, and inspired'
    - name: Enlighten”mint” 
      desc:
        - To Yoga or not to Yoga? Whether you sweat through it or slept through it, we got you covered.
        - 'Feel: Mindful, focused, and calm'
    - name: TropiCali 
      desc:
        - You hopped on a plane and just touched down on a tropical oasis. Welcome to island living, operation unwind. 
        - 'Feel: Happy, relaxed, and carefree'
    - name: Natural
      desc: 
        - Green smoothied for breakfast, ate salad for lunch, power cycled after work — that was the idea anyways.  	
        - 'Feel: Clear-headed, energized, and refreshed'


  detail:

    - left: THC
      right: '>85%'

    - left: STRAIN
      right: Hybrid

    - left: PRODUCT ORIGIN
      right: Humboldt County, CA

- name: shine
  title: Clear Cannabis Concentrate
  description:
    - Shine stronger a little longer with our 100% solvent-free, clear cannabis concentrate. We use a proprietary extraction method to distill a clean, clear oil from our High-Definition, Single Origin OG Kush. An indica-leaning hybrid, our oil is totally pure and totally potent.
    - Our concentrates can be used in loadable vape pens, oil rigs, or smeared onto joints for a little extra strength.
    - Product tested and held  to the highest standards for purity and consistent THC potency.
    - '<i>Experience: A balanced body and head high. Mellow & relaxed.</i>'
  
  thumb: shine_thumb.jpg
  image: shine.jpg
  detail:

    - left: THC
      right: '>85%'

    - left: STRAIN
      right: Hybrid

    - left: PRODUCT ORIGIN
      right: Humboldt County, CA

- name: flowers
  title: Full Blooms
  description:
    - Naturally grown and harvested under Humboldt County sunshine, our flowers are meticulously monitored and handled with the utmost care to ensure premium quality.
    - As native Humboldt growers, we have a pulse on what’s in demand to make sure we provide the newest and most exciting strains.
    - All of our flowers are lab-tested tested and held to the highest standards for purity and consistent THC potency. 
  thumb: flowers_thumb.jpg
  image: flowers.jpg
  flavors:
    - name: High-Definition OG Kush
      tag: hd
      thc: 26%
      desc:
        - One of the most legendary cannabis strains, OG Kush is a strong, Indica-leaning hybrid renowned for its powerful potency, medicinal qualities and unique taste. The strain smells and tastes like sweet lemons with a hint of woody earthiness. What makes ours High-Definition? That’s our best kept secret. 
    - name: Sunset Sherbert
      tag: sherbert
      thc: 24-26%
      desc:
        - An Indica-dominant hybrid, this is a powerful cross between the Girl Scout Cookies and Pink Panties strains. Known for its uplifting jolt of cerebral energy, Sunset Sherbet tastes like sweet citrus and honey with an earthy aftertaste. 
    - name: Sour Tangie
      tag: sour
      thc: 24%
      desc:
        - An 80% Sativa-dominant cross between East Coast Sour Diesel and Tangie, this strain is known for its extreme, mouthwatering flavor. Strong citrus notes are met with an earthy diesel aftertaste. A well-balanced strain perfect for full body relaxation. 
    - name: Black Lime Reserve
      tag: lime
      thc: 24-26%
      desc:
        - A boutique, Indica strain with a reputable Emerald Triangle heritage. A powerful cross between Northern Lights, Purple Kush and Chemdawg Special Reserve strains. Refreshing and exuberant with a pronounced mix of sweet citrus, peppery spice and juicy lime.  
  detail:

    - left: THC
      right: '24-26%'

    - left: STRAIN
      right: Hybrid

    - left: PRODUCT ORIGIN
      right: Humboldt County, CA


